--- Makefile
+++ Makefile
@@ -51,34 +58,48 @@ CONFIG_USB_AUTOSUSPEND = n
 CONFIG_HW_PWRP_DETECTION = n
 CONFIG_WIFI_TEST = n
 CONFIG_BT_COEXIST = n
-CONFIG_RTL8192CU_REDEFINE_1X1 = n
 CONFIG_INTEL_WIDI = n
 CONFIG_WAPI_SUPPORT = n
-CONFIG_EFUSE_CONFIG_FILE = n
+CONFIG_EFUSE_CONFIG_FILE = y
 CONFIG_EXT_CLK = n
 CONFIG_TRAFFIC_PROTECT = y
 CONFIG_LOAD_PHY_PARA_FROM_FILE = y
-CONFIG_CALIBRATE_TX_POWER_BY_REGULATORY = n
-CONFIG_CALIBRATE_TX_POWER_TO_MAX = n
+CONFIG_TXPWR_BY_RATE_EN = n
+CONFIG_TXPWR_LIMIT_EN = n
 CONFIG_RTW_ADAPTIVITY_EN = disable
 CONFIG_RTW_ADAPTIVITY_MODE = normal
-CONFIG_SKIP_SIGNAL_SCALE_MAPPING = n
+CONFIG_SIGNAL_SCALE_MAPPING = n
 CONFIG_80211W = n
 CONFIG_REDUCE_TX_CPU_LOADING = n
 CONFIG_BR_EXT = y
-CONFIG_ANTENNA_DIVERSITY = n
+CONFIG_TDLS = n
+CONFIG_WIFI_MONITOR = n
+CONFIG_MCC_MODE = n
+CONFIG_APPEND_VENDOR_IE_ENABLE = n
+CONFIG_RTW_NAPI = y
+CONFIG_RTW_GRO = y
+########################## Debug ###########################
+CONFIG_RTW_DEBUG = y
+# default log level is _DRV_INFO_ = 4,
+# please refer to "How_to_set_driver_debug_log_level.doc" to set the available level.
+CONFIG_RTW_LOG_LEVEL = 4
 ######################## Wake On Lan ##########################
 CONFIG_WOWLAN = n
 CONFIG_GPIO_WAKEUP = n
+CONFIG_DEFAULT_PATTERNS_EN = n
 CONFIG_WAKEUP_GPIO_IDX = default
+CONFIG_HIGH_ACTIVE = n
 CONFIG_PNO_SUPPORT = n
 CONFIG_PNO_SET_DEBUG = n
 CONFIG_AP_WOWLAN = n
 ######### Notify SDIO Host Keep Power During Syspend ##########
 CONFIG_RTW_SDIO_PM_KEEP_POWER = y
+###################### MP HW TX MODE FOR VHT #######################
+CONFIG_MP_VHT_HW_TX_MODE = n
 ###################### Platform Related #######################
 CONFIG_PLATFORM_I386_PC = y
 CONFIG_PLATFORM_ANDROID_X86 = n
+CONFIG_PLATFORM_ANDROID_INTEL_X86 = n
 CONFIG_PLATFORM_JB_X86 = n
 CONFIG_PLATFORM_ARM_S3C2K4 = n
 CONFIG_PLATFORM_ARM_PXA2XX = n
@@ -187,63 +220,65 @@ _HAL_INTFS_FILES :=       hal/hal_intf.o \
                        hal/hal_com_phycfg.o \
                        hal/hal_phy.o \
                        hal/hal_dm.o \
+                       hal/hal_btcoex_wifionly.o \
                        hal/hal_btcoex.o \
+                       hal/hal_mp.o \
+                       hal/hal_mcc.o \
                        hal/hal_hci/hal_$(HCI_NAME).o \
                        hal/led/hal_$(HCI_NAME)_led.o
 
-_OUTSRC_FILES := hal/OUTSRC/phydm_debug.o      \
-               hal/OUTSRC/phydm_AntDiv.o\
-               hal/OUTSRC/phydm_interface.o\
-               hal/OUTSRC/phydm_HWConfig.o\
-               hal/OUTSRC/phydm.o\
-               hal/OUTSRC/HalPhyRf.o\
-               hal/OUTSRC/phydm_EdcaTurboCheck.o\
-               hal/OUTSRC/phydm_DIG.o\
-               hal/OUTSRC/phydm_PathDiv.o\
-               hal/OUTSRC/phydm_RaInfo.o\
-               hal/OUTSRC/phydm_DynamicBBPowerSaving.o\
-               hal/OUTSRC/phydm_PowerTracking.o\
-               hal/OUTSRC/phydm_DynamicTxPower.o\
-               hal/OUTSRC/PhyDM_Adaptivity.o\
-               hal/OUTSRC/phydm_CfoTracking.o\
-               hal/OUTSRC/phydm_NoiseMonitor.o\
-               hal/OUTSRC/phydm_ACS.o
 
 EXTRA_CFLAGS += -I$(src)/platform
 _PLATFORM_FILES := platform/platform_ops.o
 
+EXTRA_CFLAGS += -I$(src)/hal/btc
+_BTC_FILES += hal/btc/halbtc8723bwifionly.o \
+                               hal/btc/halbtc8822bwifionly.o \
+                               hal/btc/halbtc8821cwifionly.o
 ifeq ($(CONFIG_BT_COEXIST), y)
-EXTRA_CFLAGS += -I$(src)/hal/OUTSRC-BTCoexist
-_OUTSRC_FILES += hal/OUTSRC-BTCoexist/HalBtc8188c2Ant.o \
-                               hal/OUTSRC-BTCoexist/HalBtc8192d2Ant.o \
-                               hal/OUTSRC-BTCoexist/HalBtc8192e1Ant.o \
-                               hal/OUTSRC-BTCoexist/HalBtc8192e2Ant.o \
-                               hal/OUTSRC-BTCoexist/HalBtc8723a1Ant.o \
-                               hal/OUTSRC-BTCoexist/HalBtc8723a2Ant.o \
-                               hal/OUTSRC-BTCoexist/HalBtc8723b1Ant.o \
-                               hal/OUTSRC-BTCoexist/HalBtc8723b2Ant.o \
-                               hal/OUTSRC-BTCoexist/HalBtc8812a1Ant.o \
-                               hal/OUTSRC-BTCoexist/HalBtc8812a2Ant.o \
-                               hal/OUTSRC-BTCoexist/HalBtc8821a1Ant.o \
-                               hal/OUTSRC-BTCoexist/HalBtc8821a2Ant.o \
-                               hal/OUTSRC-BTCoexist/HalBtc8821aCsr2Ant.o
-endif
-
-########### HAL_RTL8192C #################################
-
-ifeq ($(CONFIG_RTL8192C), y)
-RTL871X = rtl8192c
+_BTC_FILES += hal/btc/halbtc8192e1ant.o \
+                               hal/btc/halbtc8192e2ant.o \
+                               hal/btc/halbtc8723b1ant.o \
+                               hal/btc/halbtc8723b2ant.o \
+                               hal/btc/halbtc8812a1ant.o \
+                               hal/btc/halbtc8812a2ant.o \
+                               hal/btc/halbtc8821a1ant.o \
+                               hal/btc/halbtc8821a2ant.o \
+                               hal/btc/halbtc8703b1ant.o \
+                               hal/btc/halbtc8723d1ant.o \
+                               hal/btc/halbtc8723d2ant.o \
+                               hal/btc/halbtc8822b1ant.o \
+                               hal/btc/halbtc8822b2ant.o \
+                               hal/btc/halbtc8821c1ant.o \
+                               hal/btc/halbtc8821c2ant.o
+endif
+
+include $(TopDIR)/hal/phydm/phydm.mk
+########### HAL_RTL8188E #################################
+ifeq ($(CONFIG_RTL8188E), y)
+
+RTL871X = rtl8188e
+ifeq ($(CONFIG_SDIO_HCI), y)
+MODULE_NAME = 8189es
+endif
+
+ifeq ($(CONFIG_GSPI_HCI), y)
+MODULE_NAME = 8189es
+endif
+
 ifeq ($(CONFIG_USB_HCI), y)
-MODULE_NAME = 8192cu
+MODULE_NAME = 8188eu
 endif
+
 ifeq ($(CONFIG_PCI_HCI), y)
-MODULE_NAME = 8192ce
+MODULE_NAME = 8188ee
 endif
-EXTRA_CFLAGS += -DCONFIG_RTL8192C
+EXTRA_CFLAGS += -DCONFIG_RTL8188E
 
-_HAL_INTFS_FILES += \
-       hal/$(RTL871X)/$(RTL871X)_sreset.o \
-       hal/$(RTL871X)/$(RTL871X)_xmit.o
+_HAL_INTFS_FILES +=    hal/HalPwrSeqCmd.o \
+                                       hal/$(RTL871X)/Hal8188EPwrSeq.o\
+                                       hal/$(RTL871X)/$(RTL871X)_xmit.o\
+                                       hal/$(RTL871X)/$(RTL871X)_sreset.o
 
 _HAL_INTFS_FILES +=    hal/$(RTL871X)/$(RTL871X)_hal_init.o \
                        hal/$(RTL871X)/$(RTL871X)_phycfg.o \
@@ -251,48 +286,55 @@ _HAL_INTFS_FILES +=       hal/$(RTL871X)/$(RTL871X)_hal_init.o \
                        hal/$(RTL871X)/$(RTL871X)_dm.o \
                        hal/$(RTL871X)/$(RTL871X)_rxdesc.o \
                        hal/$(RTL871X)/$(RTL871X)_cmd.o \
+                       hal/$(RTL871X)/hal8188e_s_fw.o \
+                       hal/$(RTL871X)/hal8188e_t_fw.o \
                        hal/$(RTL871X)/$(HCI_NAME)/$(HCI_NAME)_halinit.o \
                        hal/$(RTL871X)/$(HCI_NAME)/rtl$(MODULE_NAME)_led.o \
                        hal/$(RTL871X)/$(HCI_NAME)/rtl$(MODULE_NAME)_xmit.o \
                        hal/$(RTL871X)/$(HCI_NAME)/rtl$(MODULE_NAME)_recv.o
 
+ifeq ($(CONFIG_SDIO_HCI), y)
+_HAL_INTFS_FILES += hal/$(RTL871X)/$(HCI_NAME)/$(HCI_NAME)_ops.o
+else
+ifeq ($(CONFIG_GSPI_HCI), y)
+_HAL_INTFS_FILES += hal/$(RTL871X)/$(HCI_NAME)/$(HCI_NAME)_ops.o
+else
 _HAL_INTFS_FILES += hal/$(RTL871X)/$(HCI_NAME)/$(HCI_NAME)_ops_linux.o
-
-
-ifeq ($(CONFIG_MP_INCLUDED), y)
-_HAL_INTFS_FILES += hal/$(RTL871X)/$(RTL871X)_mp.o
 endif
-
-_OUTSRC_FILES += hal/OUTSRC/$(RTL871X)/phydm_RTL8192C.o\
-                                                               hal/OUTSRC/$(RTL871X)/HalDMOutSrc8192C_CE.o
+endif
 
 ifeq ($(CONFIG_USB_HCI), y)
-_OUTSRC_FILES += hal/OUTSRC/$(RTL871X)/Hal8192CUFWImg_CE.o     \
-                                                               hal/OUTSRC/$(RTL871X)/Hal8192CUPHYImg_CE.o      \
-                                                               hal/OUTSRC/$(RTL871X)/Hal8192CUMACImg_CE.o
+_HAL_INTFS_FILES +=hal/efuse/$(RTL871X)/HalEfuseMask8188E_USB.o
 endif
-
 ifeq ($(CONFIG_PCI_HCI), y)
-_OUTSRC_FILES += hal/OUTSRC/$(RTL871X)/Hal8192CEFWImg_CE.o     \
-                                                               hal/OUTSRC/$(RTL871X)/Hal8192CEPHYImg_CE.o      \
-                                                               hal/OUTSRC/$(RTL871X)/Hal8192CEMACImg_CE.o
+_HAL_INTFS_FILES +=hal/efuse/$(RTL871X)/HalEfuseMask8188E_PCIE.o
+endif
+ifeq ($(CONFIG_SDIO_HCI), y)
+_HAL_INTFS_FILES +=hal/efuse/$(RTL871X)/HalEfuseMask8188E_SDIO.o
 endif
 
 endif
 
-########### HAL_RTL8192D #################################
-ifeq ($(CONFIG_RTL8192D), y)
-RTL871X = rtl8192d
+########### HAL_RTL8192E #################################
+ifeq ($(CONFIG_RTL8192E), y)
+
+RTL871X = rtl8192e
+ifeq ($(CONFIG_SDIO_HCI), y)
+MODULE_NAME = 8192es
+endif
+
 ifeq ($(CONFIG_USB_HCI), y)
-MODULE_NAME = 8192du
+MODULE_NAME = 8192eu
 endif
+
 ifeq ($(CONFIG_PCI_HCI), y)
-MODULE_NAME = 8192de
+MODULE_NAME = 8192ee
 endif
-EXTRA_CFLAGS += -DCONFIG_RTL8192D
-
-_HAL_INTFS_FILES += \
-       hal/$(RTL871X)/$(RTL871X)_xmit.o
+EXTRA_CFLAGS += -DCONFIG_RTL8192E
+_HAL_INTFS_FILES += hal/HalPwrSeqCmd.o \
+                                       hal/$(RTL871X)/Hal8192EPwrSeq.o\
+                                       hal/$(RTL871X)/$(RTL871X)_xmit.o\
+                                       hal/$(RTL871X)/$(RTL871X)_sreset.o
 
 _HAL_INTFS_FILES +=    hal/$(RTL871X)/$(RTL871X)_hal_init.o \
                        hal/$(RTL871X)/$(RTL871X)_phycfg.o \
@@ -300,57 +342,54 @@ _HAL_INTFS_FILES +=       hal/$(RTL871X)/$(RTL871X)_hal_init.o \
                        hal/$(RTL871X)/$(RTL871X)_dm.o \
                        hal/$(RTL871X)/$(RTL871X)_rxdesc.o \
                        hal/$(RTL871X)/$(RTL871X)_cmd.o \
+                       hal/$(RTL871X)/hal8192e_fw.o \
                        hal/$(RTL871X)/$(HCI_NAME)/$(HCI_NAME)_halinit.o \
                        hal/$(RTL871X)/$(HCI_NAME)/rtl$(MODULE_NAME)_led.o \
                        hal/$(RTL871X)/$(HCI_NAME)/rtl$(MODULE_NAME)_xmit.o \
                        hal/$(RTL871X)/$(HCI_NAME)/rtl$(MODULE_NAME)_recv.o
 
+ifeq ($(CONFIG_SDIO_HCI), y)
+_HAL_INTFS_FILES += hal/$(RTL871X)/$(HCI_NAME)/$(HCI_NAME)_ops.o
+else
+ifeq ($(CONFIG_GSPI_HCI), y)
+_HAL_INTFS_FILES += hal/$(RTL871X)/$(HCI_NAME)/$(HCI_NAME)_ops.o
+else
 _HAL_INTFS_FILES += hal/$(RTL871X)/$(HCI_NAME)/$(HCI_NAME)_ops_linux.o
-
-ifeq ($(CONFIG_MP_INCLUDED), y)
-_HAL_INTFS_FILES += hal/$(RTL871X)/$(RTL871X)_mp.o
 endif
-
-_OUTSRC_FILES += hal/OUTSRC/$(RTL871X)/phydm_RTL8192D.o\
-                                                               hal/OUTSRC/$(RTL871X)/HalDMOutSrc8192D_CE.o
-
+endif
 
 ifeq ($(CONFIG_USB_HCI), y)
-_OUTSRC_FILES += hal/OUTSRC/$(RTL871X)/Hal8192DUFWImg_CE.o \
-                                                               hal/OUTSRC/$(RTL871X)/Hal8192DUPHYImg_CE.o \
-                                                               hal/OUTSRC/$(RTL871X)/Hal8192DUMACImg_CE.o
+_HAL_INTFS_FILES +=hal/efuse/$(RTL871X)/HalEfuseMask8192E_USB.o
 endif
-
 ifeq ($(CONFIG_PCI_HCI), y)
-_OUTSRC_FILES += hal/OUTSRC/$(RTL871X)/Hal8192DEFWImg_CE.o \
-                                                               hal/OUTSRC/$(RTL871X)/Hal8192DEPHYImg_CE.o \
-                                                               hal/OUTSRC/$(RTL871X)/Hal8192DEMACImg_CE.o
+_HAL_INTFS_FILES +=hal/efuse/$(RTL871X)/HalEfuseMask8192E_PCIE.o
+endif
+ifeq ($(CONFIG_SDIO_HCI), y)
+_HAL_INTFS_FILES +=hal/efuse/$(RTL871X)/HalEfuseMask8192E_SDIO.o
 endif
 
 endif
 
-########### HAL_RTL8723A #################################
-ifeq ($(CONFIG_RTL8723A), y)
+########### HAL_RTL8812A_RTL8821A #################################
 
-RTL871X = rtl8723a
-ifeq ($(CONFIG_GSPI_HCI), y)
-MODULE_NAME = 8723as
-endif
-ifeq ($(CONFIG_SDIO_HCI), y)
-MODULE_NAME = 8723as
-endif
+ifneq ($(CONFIG_RTL8812A)_$(CONFIG_RTL8821A), n_n)
+
+RTL871X = rtl8812a
 ifeq ($(CONFIG_USB_HCI), y)
-MODULE_NAME = 8723au
+MODULE_NAME = 8812au
 endif
 ifeq ($(CONFIG_PCI_HCI), y)
-MODULE_NAME = 8723ae
+MODULE_NAME = 8812ae
+endif
+ifeq ($(CONFIG_SDIO_HCI), y)
+MODULE_NAME = 8812as
 endif
-EXTRA_CFLAGS += -DCONFIG_RTL8723A
 
-_HAL_INTFS_FILES += hal/HalPwrSeqCmd.o \
-                               hal/$(RTL871X)/Hal8723PwrSeq.o\
-                               hal/$(RTL871X)/$(RTL871X)_xmit.o \
-                               hal/$(RTL871X)/$(RTL871X)_sreset.o
+_HAL_INTFS_FILES +=  hal/HalPwrSeqCmd.o \
+                                       hal/$(RTL871X)/Hal8812PwrSeq.o \
+                                       hal/$(RTL871X)/Hal8821APwrSeq.o\
+                                       hal/$(RTL871X)/$(RTL871X)_xmit.o\
+                                       hal/$(RTL871X)/$(RTL871X)_sreset.o
 
 _HAL_INTFS_FILES +=    hal/$(RTL871X)/$(RTL871X)_hal_init.o \
                        hal/$(RTL871X)/$(RTL871X)_phycfg.o \
@@ -373,62 +412,78 @@ _HAL_INTFS_FILES += hal/$(RTL871X)/$(HCI_NAME)/$(HCI_NAME)_ops_linux.o
 endif
 endif
 
-ifeq ($(CONFIG_MP_INCLUDED), y)
-_HAL_INTFS_FILES += hal/$(RTL871X)/$(RTL871X)_mp.o
+ifeq ($(CONFIG_RTL8812A), y)
+ifeq ($(CONFIG_USB_HCI), y)
+_HAL_INTFS_FILES +=hal/efuse/$(RTL871X)/HalEfuseMask8812A_USB.o
 endif
-
-ifeq ($(CONFIG_GSPI_HCI), y)
-_OUTSRC_FILES += hal/OUTSRC/$(RTL871X)/Hal8723SHWImg_CE.o
+ifeq ($(CONFIG_PCI_HCI), y)
+_HAL_INTFS_FILES +=hal/efuse/$(RTL871X)/HalEfuseMask8812A_PCIE.o
 endif
-
-ifeq ($(CONFIG_SDIO_HCI), y)
-_OUTSRC_FILES += hal/OUTSRC/$(RTL871X)/Hal8723SHWImg_CE.o
 endif
-
+ifeq ($(CONFIG_RTL8821A), y)
 ifeq ($(CONFIG_USB_HCI), y)
-_OUTSRC_FILES += hal/OUTSRC/$(RTL871X)/Hal8723UHWImg_CE.o
+_HAL_INTFS_FILES +=hal/efuse/$(RTL871X)/HalEfuseMask8821A_USB.o
 endif
-
 ifeq ($(CONFIG_PCI_HCI), y)
-_OUTSRC_FILES += hal/OUTSRC/$(RTL871X)/Hal8723EHWImg_CE.o
+_HAL_INTFS_FILES +=hal/efuse/$(RTL871X)/HalEfuseMask8821A_PCIE.o
+endif
+ifeq ($(CONFIG_SDIO_HCI), y)
+_HAL_INTFS_FILES +=hal/efuse/$(RTL871X)/HalEfuseMask8821A_SDIO.o
+endif
 endif
 
-#hal/OUTSRC/$(RTL871X)/HalHWImg8723A_FW.o
-_OUTSRC_FILES += hal/OUTSRC/$(RTL871X)/HalHWImg8723A_BB.o\
-                                                               hal/OUTSRC/$(RTL871X)/HalHWImg8723A_MAC.o\
-                                                               hal/OUTSRC/$(RTL871X)/HalHWImg8723A_RF.o\
-                                                               hal/OUTSRC/$(RTL871X)/phydm_RegConfig8723A.o
+ifeq ($(CONFIG_RTL8812A), y)
+EXTRA_CFLAGS += -DCONFIG_RTL8812A
+_HAL_INTFS_FILES +=    hal/rtl8812a/hal8812a_fw.o
+endif
 
-_OUTSRC_FILES += hal/OUTSRC/rtl8192c/HalDMOutSrc8192C_CE.o
+ifeq ($(CONFIG_RTL8821A), y)
 
+ifeq ($(CONFIG_RTL8812A), n)
 
+RTL871X = rtl8821a
+ifeq ($(CONFIG_USB_HCI), y)
+ifeq ($(CONFIG_BT_COEXIST), y)
+MODULE_NAME := 8821au
+else
+MODULE_NAME := 8811au
+endif
+endif
+ifeq ($(CONFIG_PCI_HCI), y)
+MODULE_NAME := 8821ae
+endif
+ifeq ($(CONFIG_SDIO_HCI), y)
+MODULE_NAME := 8821as
 endif
 
+endif
 
-########### HAL_RTL8188E #################################
-ifeq ($(CONFIG_RTL8188E), y)
+EXTRA_CFLAGS += -DCONFIG_RTL8821A
 
-RTL871X = rtl8188e
-ifeq ($(CONFIG_SDIO_HCI), y)
-MODULE_NAME = 8189es
+_HAL_INTFS_FILES +=    hal/rtl8812a/hal8821a_fw.o
+
 endif
 
-ifeq ($(CONFIG_GSPI_HCI), y)
-MODULE_NAME = 8189es
 endif
 
+########### HAL_RTL8723B #################################
+ifeq ($(CONFIG_RTL8723B), y)
+
+RTL871X = rtl8723b
 ifeq ($(CONFIG_USB_HCI), y)
-MODULE_NAME = 8188eu
+MODULE_NAME = 8723bu
 endif
-
 ifeq ($(CONFIG_PCI_HCI), y)
-MODULE_NAME = 8188ee
+MODULE_NAME = 8723be
+endif
+ifeq ($(CONFIG_SDIO_HCI), y)
+MODULE_NAME = 8723bs
 endif
-EXTRA_CFLAGS += -DCONFIG_RTL8188E
 
-_HAL_INTFS_FILES +=    hal/HalPwrSeqCmd.o \
-                                       hal/$(RTL871X)/Hal8188EPwrSeq.o\
-                                       hal/$(RTL871X)/$(RTL871X)_xmit.o\
+EXTRA_CFLAGS += -DCONFIG_RTL8723B
+
+_HAL_INTFS_FILES += hal/HalPwrSeqCmd.o \
+                                       hal/$(RTL871X)/Hal8723BPwrSeq.o\
                                        hal/$(RTL871X)/$(RTL871X)_sreset.o
 
 _HAL_INTFS_FILES +=    hal/$(RTL871X)/$(RTL871X)_hal_init.o \
@@ -437,55 +492,53 @@ _HAL_INTFS_FILES +=       hal/$(RTL871X)/$(RTL871X)_hal_init.o \
                        hal/$(RTL871X)/$(RTL871X)_dm.o \
                        hal/$(RTL871X)/$(RTL871X)_rxdesc.o \
                        hal/$(RTL871X)/$(RTL871X)_cmd.o \
+                       hal/$(RTL871X)/hal8723b_fw.o
+
+_HAL_INTFS_FILES +=    \
                        hal/$(RTL871X)/$(HCI_NAME)/$(HCI_NAME)_halinit.o \
                        hal/$(RTL871X)/$(HCI_NAME)/rtl$(MODULE_NAME)_led.o \
                        hal/$(RTL871X)/$(HCI_NAME)/rtl$(MODULE_NAME)_xmit.o \
                        hal/$(RTL871X)/$(HCI_NAME)/rtl$(MODULE_NAME)_recv.o
 
-ifeq ($(CONFIG_SDIO_HCI), y)
-_HAL_INTFS_FILES += hal/$(RTL871X)/$(HCI_NAME)/$(HCI_NAME)_ops.o
+ifeq ($(CONFIG_PCI_HCI), y)
+_HAL_INTFS_FILES += hal/$(RTL871X)/$(HCI_NAME)/$(HCI_NAME)_ops_linux.o
 else
-ifeq ($(CONFIG_GSPI_HCI), y)
 _HAL_INTFS_FILES += hal/$(RTL871X)/$(HCI_NAME)/$(HCI_NAME)_ops.o
-else
-_HAL_INTFS_FILES += hal/$(RTL871X)/$(HCI_NAME)/$(HCI_NAME)_ops_linux.o
-endif
 endif
 
-ifeq ($(CONFIG_MP_INCLUDED), y)
-_HAL_INTFS_FILES += hal/$(RTL871X)/$(RTL871X)_mp.o
+ifeq ($(CONFIG_USB_HCI), y)
+_HAL_INTFS_FILES +=hal/efuse/$(RTL871X)/HalEfuseMask8723B_USB.o
 endif
-
-#hal/OUTSRC/$(RTL871X)/Hal8188EFWImg_CE.o
-_OUTSRC_FILES += hal/OUTSRC/$(RTL871X)/HalHWImg8188E_MAC.o\
-               hal/OUTSRC/$(RTL871X)/HalHWImg8188E_BB.o\
-               hal/OUTSRC/$(RTL871X)/HalHWImg8188E_RF.o\
-               hal/OUTSRC/$(RTL871X)/HalHWImg8188E_FW.o\
-               hal/OUTSRC/$(RTL871X)/HalPhyRf_8188e.o\
-               hal/OUTSRC/$(RTL871X)/phydm_RegConfig8188E.o\
-               hal/OUTSRC/$(RTL871X)/Hal8188ERateAdaptive.o\
-               hal/OUTSRC/$(RTL871X)/phydm_RTL8188E.o
-
+ifeq ($(CONFIG_PCI_HCI), y)
+_HAL_INTFS_FILES +=hal/efuse/$(RTL871X)/HalEfuseMask8723B_PCIE.o
 endif
-
-########### HAL_RTL8192E #################################
-ifeq ($(CONFIG_RTL8192E), y)
-
-RTL871X = rtl8192e
 ifeq ($(CONFIG_SDIO_HCI), y)
-MODULE_NAME = 8192es
+_HAL_INTFS_FILES +=hal/efuse/$(RTL871X)/HalEfuseMask8723B_SDIO.o
 endif
 
-ifeq ($(CONFIG_USB_HCI), y)
-MODULE_NAME = 8192eu
 endif
 
+########### HAL_RTL8814A #################################
+ifeq ($(CONFIG_RTL8814A), y)
+## ADD NEW VHT MP HW TX MODE ##
+#EXTRA_CFLAGS += -DCONFIG_MP_VHT_HW_TX_MODE
+#CONFIG_MP_VHT_HW_TX_MODE = y
+##########################################
+RTL871X = rtl8814a
+ifeq ($(CONFIG_USB_HCI), y)
+MODULE_NAME = 8814au
+endif
 ifeq ($(CONFIG_PCI_HCI), y)
-MODULE_NAME = 8192ee
+MODULE_NAME = 8814ae
 endif
-EXTRA_CFLAGS += -DCONFIG_RTL8192E
-_HAL_INTFS_FILES += hal/HalPwrSeqCmd.o \
-                                       hal/$(RTL871X)/Hal8192EPwrSeq.o\
+ifeq ($(CONFIG_SDIO_HCI), y)
+MODULE_NAME = 8814as
+endif
+
+EXTRA_CFLAGS += -DCONFIG_RTL8814A
+
+_HAL_INTFS_FILES +=  hal/HalPwrSeqCmd.o \
+                                       hal/$(RTL871X)/Hal8814PwrSeq.o \
                                        hal/$(RTL871X)/$(RTL871X)_xmit.o\
                                        hal/$(RTL871X)/$(RTL871X)_sreset.o
 
@@ -495,6 +548,10 @@ _HAL_INTFS_FILES +=        hal/$(RTL871X)/$(RTL871X)_hal_init.o \
                        hal/$(RTL871X)/$(RTL871X)_dm.o \
                        hal/$(RTL871X)/$(RTL871X)_rxdesc.o \
                        hal/$(RTL871X)/$(RTL871X)_cmd.o \
+                       hal/$(RTL871X)/hal8814a_fw.o
+
+
+_HAL_INTFS_FILES +=    \
                        hal/$(RTL871X)/$(HCI_NAME)/$(HCI_NAME)_halinit.o \
                        hal/$(RTL871X)/$(HCI_NAME)/rtl$(MODULE_NAME)_led.o \
                        hal/$(RTL871X)/$(HCI_NAME)/rtl$(MODULE_NAME)_xmit.o \
@@ -510,40 +567,36 @@ _HAL_INTFS_FILES += hal/$(RTL871X)/$(HCI_NAME)/$(HCI_NAME)_ops_linux.o
 endif
 endif
 
-ifeq ($(CONFIG_MP_INCLUDED), y)
-_HAL_INTFS_FILES += hal/$(RTL871X)/$(RTL871X)_mp.o
+ifeq ($(CONFIG_USB_HCI), y)
+_HAL_INTFS_FILES +=hal/efuse/$(RTL871X)/HalEfuseMask8814A_USB.o
 endif
-
-#hal/OUTSRC/$(RTL871X)/HalHWImg8188E_FW.o
-_OUTSRC_FILES += hal/OUTSRC/$(RTL871X)/HalHWImg8192E_MAC.o\
-               hal/OUTSRC/$(RTL871X)/HalHWImg8192E_BB.o\
-               hal/OUTSRC/$(RTL871X)/HalHWImg8192E_RF.o\
-               hal/OUTSRC/$(RTL871X)/HalHWImg8192E_FW.o\
-               hal/OUTSRC/$(RTL871X)/HalPhyRf_8192e.o\
-               hal/OUTSRC/$(RTL871X)/phydm_RegConfig8192E.o\
-               hal/OUTSRC/$(RTL871X)/phydm_RTL8192E.o
-
+ifeq ($(CONFIG_PCI_HCI), y)
+_HAL_INTFS_FILES +=hal/efuse/$(RTL871X)/HalEfuseMask8814A_PCIE.o
 endif
 
-########### HAL_RTL8812A_RTL8821A #################################
+endif
 
-ifneq ($(CONFIG_RTL8812A)_$(CONFIG_RTL8821A), n_n)
+########### HAL_RTL8723C #################################
+ifeq ($(CONFIG_RTL8723C), y)
 
-RTL871X = rtl8812a
+RTL871X = rtl8703b
 ifeq ($(CONFIG_USB_HCI), y)
-MODULE_NAME = 8812au
+MODULE_NAME = 8723cu
+MODULE_SUB_NAME = 8703bu
 endif
 ifeq ($(CONFIG_PCI_HCI), y)
-MODULE_NAME = 8812ae
+MODULE_NAME = 8723ce
+MODULE_SUB_NAME = 8703be
 endif
 ifeq ($(CONFIG_SDIO_HCI), y)
-MODULE_NAME = 8812as
+MODULE_NAME = 8723cs
+MODULE_SUB_NAME = 8703bs
 endif
 
-_HAL_INTFS_FILES +=  hal/HalPwrSeqCmd.o \
-                                       hal/$(RTL871X)/Hal8812PwrSeq.o \
-                                       hal/$(RTL871X)/Hal8821APwrSeq.o\
-                                       hal/$(RTL871X)/$(RTL871X)_xmit.o\
+EXTRA_CFLAGS += -DCONFIG_RTL8703B
+
+_HAL_INTFS_FILES += hal/HalPwrSeqCmd.o \
+                                       hal/$(RTL871X)/Hal8703BPwrSeq.o\
                                        hal/$(RTL871X)/$(RTL871X)_sreset.o
 
 _HAL_INTFS_FILES +=    hal/$(RTL871X)/$(RTL871X)_hal_init.o \
@@ -552,86 +605,101 @@ _HAL_INTFS_FILES +=      hal/$(RTL871X)/$(RTL871X)_hal_init.o \
                        hal/$(RTL871X)/$(RTL871X)_dm.o \
                        hal/$(RTL871X)/$(RTL871X)_rxdesc.o \
                        hal/$(RTL871X)/$(RTL871X)_cmd.o \
+                       hal/$(RTL871X)/hal8703b_fw.o
+
+_HAL_INTFS_FILES +=    \
                        hal/$(RTL871X)/$(HCI_NAME)/$(HCI_NAME)_halinit.o \
-                       hal/$(RTL871X)/$(HCI_NAME)/rtl$(MODULE_NAME)_led.o \
-                       hal/$(RTL871X)/$(HCI_NAME)/rtl$(MODULE_NAME)_xmit.o \
-                       hal/$(RTL871X)/$(HCI_NAME)/rtl$(MODULE_NAME)_recv.o
+                       hal/$(RTL871X)/$(HCI_NAME)/rtl$(MODULE_SUB_NAME)_led.o \
+                       hal/$(RTL871X)/$(HCI_NAME)/rtl$(MODULE_SUB_NAME)_xmit.o \
+                       hal/$(RTL871X)/$(HCI_NAME)/rtl$(MODULE_SUB_NAME)_recv.o
 
-ifeq ($(CONFIG_SDIO_HCI), y)
-_HAL_INTFS_FILES += hal/$(RTL871X)/$(HCI_NAME)/$(HCI_NAME)_ops.o
+ifeq ($(CONFIG_PCI_HCI), y)
+_HAL_INTFS_FILES += hal/$(RTL871X)/$(HCI_NAME)/$(HCI_NAME)_ops_linux.o
 else
-ifeq ($(CONFIG_GSPI_HCI), y)
 _HAL_INTFS_FILES += hal/$(RTL871X)/$(HCI_NAME)/$(HCI_NAME)_ops.o
-else
-_HAL_INTFS_FILES += hal/$(RTL871X)/$(HCI_NAME)/$(HCI_NAME)_ops_linux.o
-endif
 endif
 
-ifeq ($(CONFIG_MP_INCLUDED), y)
-_HAL_INTFS_FILES += hal/$(RTL871X)/$(RTL871X)_mp.o
+ifeq ($(CONFIG_USB_HCI), y)
+_HAL_INTFS_FILES +=hal/efuse/$(RTL871X)/HalEfuseMask8703B_USB.o
 endif
-
-ifeq ($(CONFIG_RTL8812A), y)
-EXTRA_CFLAGS += -DCONFIG_RTL8812A
-_OUTSRC_FILES += hal/OUTSRC/$(RTL871X)/HalHWImg8812A_FW.o\
-               hal/OUTSRC/$(RTL871X)/HalHWImg8812A_MAC.o\
-               hal/OUTSRC/$(RTL871X)/HalHWImg8812A_BB.o\
-               hal/OUTSRC/$(RTL871X)/HalHWImg8812A_RF.o\
-               hal/OUTSRC/$(RTL871X)/HalPhyRf_8812A.o\
-               hal/OUTSRC/$(RTL871X)/phydm_RegConfig8812A.o\
-               hal/OUTSRC/$(RTL871X)/phydm_RTL8812A.o
+ifeq ($(CONFIG_PCI_HCI), y)
+_HAL_INTFS_FILES +=hal/efuse/$(RTL871X)/HalEfuseMask8703B_PCIE.o
 endif
 
-ifeq ($(CONFIG_RTL8821A), y)
+endif
 
-ifeq ($(CONFIG_RTL8812A), n)
+########### HAL_RTL8723D #################################
+ifeq ($(CONFIG_RTL8723D), y)
 
-RTL871X = rtl8821a
+RTL871X = rtl8723d
 ifeq ($(CONFIG_USB_HCI), y)
-MODULE_NAME := 8821au
+MODULE_NAME = 8723du
+MODULE_SUB_NAME = 8723du
 endif
 ifeq ($(CONFIG_PCI_HCI), y)
-MODULE_NAME := 8821ae
+MODULE_NAME = 8723de
+MODULE_SUB_NAME = 8723de
 endif
 ifeq ($(CONFIG_SDIO_HCI), y)
-MODULE_NAME := 8821as
+MODULE_NAME = 8723ds
+MODULE_SUB_NAME = 8723ds
 endif
 
-endif
+EXTRA_CFLAGS += -DCONFIG_RTL8723D
 
-EXTRA_CFLAGS += -DCONFIG_RTL8821A
-_OUTSRC_FILES += hal/OUTSRC/rtl8821a/HalHWImg8821A_FW.o\
-               hal/OUTSRC/rtl8821a/HalHWImg8821A_MAC.o\
-               hal/OUTSRC/rtl8821a/HalHWImg8821A_BB.o\
-               hal/OUTSRC/rtl8821a/HalHWImg8821A_RF.o\
-               hal/OUTSRC/rtl8812a/HalPhyRf_8812A.o\
-               hal/OUTSRC/rtl8821a/HalPhyRf_8821A.o\
-               hal/OUTSRC/rtl8821a/phydm_RegConfig8821A.o\
-               hal/OUTSRC/rtl8821a/phydm_RTL8821A.o\
-               hal/OUTSRC/rtl8821a/PhyDM_IQK_8821A.o
+_HAL_INTFS_FILES += hal/HalPwrSeqCmd.o \
+                                       hal/$(RTL871X)/Hal8723DPwrSeq.o\
+                                       hal/$(RTL871X)/$(RTL871X)_sreset.o
+
+_HAL_INTFS_FILES +=    hal/$(RTL871X)/$(RTL871X)_hal_init.o \
+                       hal/$(RTL871X)/$(RTL871X)_phycfg.o \
+                       hal/$(RTL871X)/$(RTL871X)_rf6052.o \
+                       hal/$(RTL871X)/$(RTL871X)_dm.o \
+                       hal/$(RTL871X)/$(RTL871X)_rxdesc.o \
+                       hal/$(RTL871X)/$(RTL871X)_cmd.o \
+                       hal/$(RTL871X)/hal8723d_fw.o \
+                       hal/$(RTL871X)/$(RTL871X)_lps_poff.o
+
+
+_HAL_INTFS_FILES +=    \
+                       hal/$(RTL871X)/$(HCI_NAME)/$(HCI_NAME)_halinit.o \
+                       hal/$(RTL871X)/$(HCI_NAME)/rtl$(MODULE_SUB_NAME)_led.o \
+                       hal/$(RTL871X)/$(HCI_NAME)/rtl$(MODULE_SUB_NAME)_xmit.o \
+                       hal/$(RTL871X)/$(HCI_NAME)/rtl$(MODULE_SUB_NAME)_recv.o
+
+ifeq ($(CONFIG_PCI_HCI), y)
+_HAL_INTFS_FILES += hal/$(RTL871X)/$(HCI_NAME)/$(HCI_NAME)_ops_linux.o
+else
+_HAL_INTFS_FILES += hal/$(RTL871X)/$(HCI_NAME)/$(HCI_NAME)_ops.o
 endif
 
+ifeq ($(CONFIG_USB_HCI), y)
+_HAL_INTFS_FILES +=hal/efuse/$(RTL871X)/HalEfuseMask8723D_USB.o
+endif
+ifeq ($(CONFIG_PCI_HCI), y)
+_HAL_INTFS_FILES +=hal/efuse/$(RTL871X)/HalEfuseMask8723D_PCIE.o
+endif
 
 endif
 
-########### HAL_RTL8723B #################################
-ifeq ($(CONFIG_RTL8723B), y)
+########### HAL_RTL8188F #################################
+ifeq ($(CONFIG_RTL8188F), y)
 
-RTL871X = rtl8723b
+RTL871X = rtl8188f
 ifeq ($(CONFIG_USB_HCI), y)
-MODULE_NAME = 8723bu
+MODULE_NAME = 8188fu
 endif
 ifeq ($(CONFIG_PCI_HCI), y)
-MODULE_NAME = 8723be
+MODULE_NAME = 8188fe
 endif
 ifeq ($(CONFIG_SDIO_HCI), y)
-MODULE_NAME = 8723bs
+MODULE_NAME = 8189fs
 endif
 
-EXTRA_CFLAGS += -DCONFIG_RTL8723B
+EXTRA_CFLAGS += -DCONFIG_RTL8188F
 
 _HAL_INTFS_FILES += hal/HalPwrSeqCmd.o \
-                                       hal/$(RTL871X)/Hal8723BPwrSeq.o\
+                                       hal/$(RTL871X)/Hal8188FPwrSeq.o\
                                        hal/$(RTL871X)/$(RTL871X)_sreset.o
 
 _HAL_INTFS_FILES +=    hal/$(RTL871X)/$(RTL871X)_hal_init.o \
@@ -640,7 +708,7 @@ _HAL_INTFS_FILES += hal/$(RTL871X)/$(RTL871X)_hal_init.o \
                        hal/$(RTL871X)/$(RTL871X)_dm.o \
                        hal/$(RTL871X)/$(RTL871X)_rxdesc.o \
                        hal/$(RTL871X)/$(RTL871X)_cmd.o \
-
+                       hal/$(RTL871X)/hal8188f_fw.o
 
 _HAL_INTFS_FILES +=    \
                        hal/$(RTL871X)/$(HCI_NAME)/$(HCI_NAME)_halinit.o \
@@ -654,21 +722,26 @@ else
 _HAL_INTFS_FILES += hal/$(RTL871X)/$(HCI_NAME)/$(HCI_NAME)_ops.o
 endif
 
-ifeq ($(CONFIG_MP_INCLUDED), y)
-_HAL_INTFS_FILES += hal/$(RTL871X)/$(RTL871X)_mp.o
+ifeq ($(CONFIG_USB_HCI), y)
+_HAL_INTFS_FILES +=hal/efuse/$(RTL871X)/HalEfuseMask8188F_USB.o
 endif
 
-_OUTSRC_FILES += hal/OUTSRC/$(RTL871X)/HalHWImg8723B_BB.o\
-                                                               hal/OUTSRC/$(RTL871X)/HalHWImg8723B_MAC.o\
-                                                               hal/OUTSRC/$(RTL871X)/HalHWImg8723B_RF.o\
-                                                               hal/OUTSRC/$(RTL871X)/HalHWImg8723B_FW.o\
-                                                               hal/OUTSRC/$(RTL871X)/HalHWImg8723B_MP.o\
-                                                               hal/OUTSRC/$(RTL871X)/phydm_RegConfig8723B.o\
-                                                               hal/OUTSRC/$(RTL871X)/HalPhyRf_8723B.o\
-                                                               hal/OUTSRC/$(RTL871X)/phydm_RTL8723B.o
+ifeq ($(CONFIG_SDIO_HCI), y)
+_HAL_INTFS_FILES +=hal/efuse/$(RTL871X)/HalEfuseMask8188F_SDIO.o
+endif
 
 endif
 
+########### HAL_RTL8822B #################################
+ifeq ($(CONFIG_RTL8822B), y)
+include $(TopDIR)/rtl8822b.mk
+endif
+
+########### HAL_RTL8821C #################################
+ifeq ($(CONFIG_RTL8821C), y)
+include $(TopDIR)/rtl8821c.mk
+endif
+
 ########### AUTO_CFG  #################################
 
 ifeq ($(CONFIG_AUTOCFG_CP), y)
@@ -718,10 +794,6 @@ ifeq ($(CONFIG_BT_COEXIST), y)
 EXTRA_CFLAGS += -DCONFIG_BT_COEXIST
 endif
 
-ifeq ($(CONFIG_RTL8192CU_REDEFINE_1X1), y)
-EXTRA_CFLAGS += -DRTL8192C_RECONFIG_TO_1T1R
-endif
-
 ifeq ($(CONFIG_INTEL_WIDI), y)
 EXTRA_CFLAGS += -DCONFIG_INTEL_WIDI
 endif
@@ -867,13 +976,52 @@ EXTRA_CFLAGS += -DCONFIG_BR_EXT
 EXTRA_CFLAGS += '-DCONFIG_BR_EXT_BRNAME="'$(BR_NAME)'"'
 endif
 
-ifeq ($(CONFIG_ANTENNA_DIVERSITY), y)
-EXTRA_CFLAGS += -DCONFIG_ANTENNA_DIVERSITY
+
+ifeq ($(CONFIG_TDLS), y)
+EXTRA_CFLAGS += -DCONFIG_TDLS
+endif
+
+ifeq ($(CONFIG_WIFI_MONITOR), y)
+EXTRA_CFLAGS += -DCONFIG_WIFI_MONITOR
+endif
+
+ifeq ($(CONFIG_MCC_MODE), y)
+EXTRA_CFLAGS += -DCONFIG_MCC_MODE
+endif
+
+ifeq ($(CONFIG_RTW_NAPI), y)
+EXTRA_CFLAGS += -DCONFIG_RTW_NAPI
 endif
 
+ifeq ($(CONFIG_RTW_GRO), y)
+EXTRA_CFLAGS += -DCONFIG_RTW_GRO
+endif
+
+ifeq ($(CONFIG_MP_VHT_HW_TX_MODE), y)
+EXTRA_CFLAGS += -DCONFIG_MP_VHT_HW_TX_MODE
+ifeq ($(CONFIG_PLATFORM_I386_PC), y)
+## For I386 X86 ToolChain use Hardware FLOATING
+EXTRA_CFLAGS += -mhard-float
+else
+## For ARM ToolChain use Hardware FLOATING
+EXTRA_CFLAGS += -mfloat-abi=hard
+endif
+endif
+
+ifeq ($(CONFIG_APPEND_VENDOR_IE_ENABLE), y)
+EXTRA_CFLAGS += -DCONFIG_APPEND_VENDOR_IE_ENABLE
+endif
+
+ifeq ($(CONFIG_RTW_DEBUG), y)
+EXTRA_CFLAGS += -DCONFIG_RTW_DEBUG
+EXTRA_CFLAGS += -DRTW_LOG_LEVEL=$(CONFIG_RTW_LOG_LEVEL)
+endif
+
+EXTRA_CFLAGS += -DDM_ODM_SUPPORT_TYPE=0x04
 
 ifeq ($(CONFIG_PLATFORM_I386_PC), y)
 EXTRA_CFLAGS += -DCONFIG_LITTLE_ENDIAN
+EXTRA_CFLAGS += -DCONFIG_IOCTL_CFG80211 -DRTW_USE_CFG80211_STA_EVENT
 SUBARCH := $(shell uname -m | sed -e s/i.86/i386/)
 ARCH ?= $(SUBARCH)
 CROSS_COMPILE ?=
@@ -984,7 +1205,14 @@ KSRC:= /usr/src/Mstar_kernel/2.6.28.9/
 endif
 
 ifeq ($(CONFIG_PLATFORM_MSTAR), y)
-EXTRA_CFLAGS += -DCONFIG_LITTLE_ENDIAN -DCONFIG_PLATFORM_MSTAR                 #-DCONFIG_PLATFORM_MSTAR_SCAN_BEFORE_CONNECT
+EXTRA_CFLAGS += -DCONFIG_CONCURRENT_MODE
+EXTRA_CFLAGS += -DCONFIG_IOCTL_CFG80211 -DRTW_USE_CFG80211_STA_EVENT
+EXTRA_CFLAGS += -DCONFIG_LITTLE_ENDIAN
+EXTRA_CFLAGS += -DCONFIG_PLATFORM_MSTAR
+EXTRA_CFLAGS += -DCONFIG_PLATFORM_MSTAR_HIGH
+ifeq ($(CONFIG_USB_HCI), y)
+EXTRA_CFLAGS += -DCONFIG_USE_USB_BUFFER_ALLOC_TX -DCONFIG_FIX_NR_BULKIN_BUFFER
+endif
 ARCH:=arm
 CROSS_COMPILE:= /usr/src/bin/arm-none-linux-gnueabi-
 KVER:= 3.1.10
@@ -1647,6 +1989,7 @@ rtk_core :=       core/rtw_cmd.o \
                core/rtw_ieee80211.o \
                core/rtw_mlme.o \
                core/rtw_mlme_ext.o \
+               core/rtw_mi.o \
                core/rtw_wlan_util.o \
                core/rtw_vht.o \
                core/rtw_pwrctrl.o \
@@ -1660,10 +2003,15 @@ rtk_core :=     core/rtw_cmd.o \
                core/rtw_br_ext.o \
                core/rtw_iol.o \
                core/rtw_sreset.o \
+               core/rtw_btcoex_wifionly.o \
                core/rtw_btcoex.o \
                core/rtw_beamforming.o \
                core/rtw_odm.o \
-               core/efuse/rtw_efuse.o
+               core/efuse/rtw_efuse.o
+
+ifeq ($(CONFIG_SDIO_HCI), y)
+rtk_core += core/rtw_sdio.o
+endif
 
 $(MODULE_NAME)-y += $(rtk_core)
 
@@ -1674,21 +2022,15 @@ $(MODULE_NAME)-$(CONFIG_WAPI_SUPPORT) += core/rtw_wapi.o        \
 
 $(MODULE_NAME)-y += $(_OS_INTFS_FILES)
 $(MODULE_NAME)-y += $(_HAL_INTFS_FILES)
-$(MODULE_NAME)-y += $(_OUTSRC_FILES)
+$(MODULE_NAME)-y += $(_PHYDM_FILES)
+$(MODULE_NAME)-y += $(_BTC_FILES)
 $(MODULE_NAME)-y += $(_PLATFORM_FILES)
 
-$(MODULE_NAME)-$(CONFIG_MP_INCLUDED) += core/rtw_mp.o \
-                                       core/rtw_mp_ioctl.o
+$(MODULE_NAME)-$(CONFIG_MP_INCLUDED) += core/rtw_mp.o
 
-ifeq ($(CONFIG_RTL8723A), y)
-$(MODULE_NAME)-$(CONFIG_MP_INCLUDED)+= core/rtw_bt_mp.o
-endif
 ifeq ($(CONFIG_RTL8723B), y)
 $(MODULE_NAME)-$(CONFIG_MP_INCLUDED)+= core/rtw_bt_mp.o
 endif
-ifeq ($(CONFIG_RTL8821A), y)
-$(MODULE_NAME)-$(CONFIG_MP_INCLUDED)+= core/rtw_bt_mp.o
-endif
 
 obj-$(CONFIG_RTL8812AU) := $(MODULE_NAME).o
 
@@ -1754,9 +2130,8 @@ config_r:
 .PHONY: modules clean
 
 clean:
-       cd hal/OUTSRC/ ; rm -fr */*.mod.c */*.mod */*.o */.*.cmd */*.ko
-       cd hal/OUTSRC/ ; rm -fr *.mod.c *.mod *.o .*.cmd *.ko
-       cd hal/led ; rm -fr *.mod.c *.mod *.o .*.cmd *.ko
+       #$(MAKE) -C $(KSRC) M=$(shell pwd) clean
+       cd hal ; rm -fr */*/*/*.mod.c */*/*/*.mod */*/*/*.o */*/*/.*.cmd */*/*/*.ko
        cd hal ; rm -fr */*/*.mod.c */*/*.mod */*/*.o */*/.*.cmd */*/*.ko
        cd hal ; rm -fr */*.mod.c */*.mod */*.o */.*.cmd */*.ko
        cd hal ; rm -fr *.mod.c *.mod *.o .*.cmd *.ko
